apckane/github-flow-test-201805

tak024
github flow test のため tak024 file を追加
=> add tak024 file

giiiiiyu, {giiiiiyu}
githu flow testの為、giiiiiyu fileを追加
=> add giiiiiyu file

apciij
github flow test  のため apciij file を追加
=> add apciij file

K-Furuki3
github flow testのために K-Furuki3ファイルを追加
=> add K-Furuki3 file

hi-sugawara
github flow test のためファイル hi-sugawara file を追加
=> add hi-sugawara file

gitHaraAPC
=> add gitHaraAPC file

{yingoodboy}
for github test added from yingoodboy
=> add {yingoodboy} file

{t-kazuno}
github flow testのためt-kazuno fileを追加
=> add {t-kazuno} file

{apc-ogi}
github flow testのため　apc-ogi　fileを追加
=> add{apc-ogi}file

apc-kusume
Github flow test のためファイルを追加しました
=> add apc-kusume file

bug_contain_scripts/typo.sh
=> action_topic_yIn_typo

bug_contain_scripts/loop.sh
=> Edit loop.sh

bug_contain_scripts/function.sh
=> Bug function.sh ( hi-sugawara )

bug_contain_scripts/for.sh
=> add for.sh file

bug_contain_scripts/test.sh
=> fix test.sh file

kokokokokokokokokokoko
github flow test のため kokokokokokokokokokoko file を追加
=> add kokokokokokokokokokoko file

apcarakawa
github flow test のため apcarakawa file を追加
=> add apcarakawa file

park9311
github flow test のため park9311 file を追加
=> add park9311 file

jhasegawa
=> add jhasegawa file

park9311
=> add park9311_bug file

bug_contain_scripts/plus.py, ikegami0413
=> add ikegami0413 file

bug_contain_scripts/print.py
* 組み込み関数名のミスを修正
* 不要な中間変数を削除
```bash
$ python3 bug_contain_scripts/print.py
Test
```
=> print.pyのビルドエラー修正＋最適化

{kuni193}
=> add{kuni193}file

fix_indent.py
=> add fix_indent.py file

bug_contain_scripts/calc.sh
=> fix calc.sh

bug_contain_scripts/delete.py
=> big fix delete.py

apcarakawa, bug_contain_scripts/array.py, bug_contain_scripts/bug-fix
=> Topic branch apcarakawa

apc-tokusho, bug_contain_scripts/word.py
=> Topic branch apc tokusho

typo.sh
=> add typo.sh file
